### ISSUE TITLE
Se souvenir de moi

### ISSUE THREAD

**Issue by LSarribouette** [LSarribouette/rocket-go#6]
https://github.com/LSarribouette/rocket-go/blob/924104e988b66e97dd2fca3d647467513e1a8c9f/config/packages/security.yaml#L24-L26

@caliendojulien 
Est-ce la bonne façon de mettre en place le "remember me" ?

**Comment by caliendojulien** [comment]
@LSarribouette En retirant les commentaires du twig de login en plus .... oui

**Comment by caliendojulien** [comment]
Pour vérifier que ca fonctionne, regarde les cookies dans les "outils de développement" de ton navigateur.

**Comment by LSarribouette** [comment]
Ca fonctionne, merci !
