### ISSUE TITLE
Réinitialisation du mot de passe et redirection

### ISSUE THREAD

**Issue by LSarribouette** [LSarribouette/rocket-go#9]
https://github.com/LSarribouette/rocket-go/blob/361b6cbd240ebe6a0a3de75e9d0ee9f81731857b/src/Controller/ResetPasswordController.php#L122

@caliendojulien 
J'aimerais qu'après avoir réinitialiser son mot de passe, l'utilisateur soit automatiquement connecté et rediriger vers la liste des sorties. Comme quand il s'enregistre en fait.
Est-ce que c'est faisable ? Si oui, aurais-tu un indice ?
Je veux faire ça pour pouvoir utiliser le même formulaire dans Mon profil > Réinitialiser mon mot de passe.

**Comment by caliendojulien** [comment]
Je ne sais pas du tout. Faut que je regarde.

**Comment by caliendojulien** [comment]
@LSarribouette  :
Je pense que c'est faisable mais j'aime pas trop l'idée.
En gros, ca sous entend que tu va trimballer le mot de passe, en clair,, entré par l'utilisateur, de contrôleur en contrôleur. Pour passer de celui qui reset a celui qui loggue.

**Comment by LSarribouette** [comment]
D'accord, mauvaise idée du coup. J'avais un doute en effet... Merci !
